### ISSUE TITLE
[bug] 폰트 적용 안되는 버그

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/store-1#32]
## ⚠️ 버그 설명

<img width="151" alt="Screen Shot 2021-08-18 at 7 38 06 PM" src="https://user-images.githubusercontent.com/5162089/129884200-0a4744d8-16d5-4e5d-a65b-46fc0800ee72.png">

![image](https://user-images.githubusercontent.com/5162089/129884300-2673a256-6905-40ca-b64a-79c77269e1cc.png)

reset css에서 `font: inherit;`로 적용돼 있어서 `* { }`에 작성한 폰트가 적용이 안되고 있습니다.
그렇기에 `body { }`안에 폰트 작성을 옮겨 야 합니다.

```css
* {
  box-sizing: border-box;
}
body {
  font-family: 'NotoSans', 'DoHyeon', sans-serif;
}
```

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 폰트 적용을 *에서 body로 옮기기

## 🚧 주의 사항

없음
